package com.example.demo.controller;

import java.nio.charset.StandardCharsets;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;

import com.example.demo.model.Producto;
import com.example.demo.repository.ProductoRepo;

@Controller
@RequestMapping("/admin")
public class AdminController {

    @Autowired
    private ProductoRepo productoRepo;

    @GetMapping("/export")
    public ResponseEntity<byte[]> exportDatabase() {
        StringBuilder sql = new StringBuilder();

        sql.append("CREATE TABLE IF NOT EXISTS producto (\n");
        sql.append("    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n");
        sql.append("    name VARCHAR(255),\n");
        sql.append("    price DOUBLE PRECISION NOT NULL\n");
        sql.append(");\n\n");

        for (Producto product : productoRepo.findAll()) {
            String name = product.getName() == null
                    ? "NULL" : "'" + product.getName().replace("'", "''") + "'";

            sql.append("INSERT INTO producto (id, name, price) VALUES (");
            sql.append(product.getId());
            sql.append(", ");
            sql.append(name);
            sql.append(", ");
            sql.append(product.getPrice());
            sql.append(");\n");
        }

        return ResponseEntity.ok()
                .header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=\"products.sql\"")
                .contentType(MediaType.parseMediaType("application/sql;charset=UTF-8"))
                .body(sql.toString().getBytes(StandardCharsets.UTF_8));
    }
}
